# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

################################################################################
# This file contains the Metrics and EncodingConfigs used in
# envelope_maker_test.cc
#
# It is compiled into envelope_maker_test_config.h which is included into the
# test.
################################################################################

################################################################################
#  Metrics
################################################################################
metric_configs:
# Metric 1 has one string part, and local time_zone_policy.
- id: 1
  name: "First"
  time_zone_policy: UTC
  parts:
    "Part1":

# Metric 2 has one string part, and local time_zone_policy.
- id: 2
  name: "Second"
  time_zone_policy: UTC
  parts:
    "Part1":

# Metric 3 has one string part, and local time_zone_policy.
- id: 3
  name: "Third"
  time_zone_policy: UTC
  parts:
    "Part1":

################################################################################
#  EncodingConfigs
################################################################################
encoding_configs:

# EncodingConfig 1 is Forculus.
- id: 1
  name: "Forculus"
  forculus:
    threshold: 20

# EncodingConfig 2 is Basic RAPPOR with string categories.
- id: 2
  name: "BasicRappor"
  basic_rappor:
    prob_0_becomes_1: 0.25
    prob_1_stays_1: 0.75
    string_categories:
      category:
      - "Apple"
      - "Banana"
      - "Cantaloupe"

# EncodingConfig 3 is the NoOp encoding.
- id: 3
  name: "NoOp"
  no_op_encoding:
